document.addEventListener('DOMContentLoaded', function () {
    const seasonSelect = document.getElementById('season');
    const divisionSelect = document.getElementById('division');
    const perflistSelect = document.getElementById('perflist');

    const performanceLists = {
        '2024_out': {
            'd1': [
                { id: '4515', name: '2024 Div. I Combined List' },
                { id: '4573', name: 'Div. I East Qualifying List' },
                { id: '4574', name: 'Div. I West Qualifying List' },
                { id: '4686', name: 'DI Great Lakes Region' },
                { id: '4687', name: 'DI Mid-Atlantic Region' },
                { id: '4688', name: 'DI Midwest Region' },
                { id: '4689', name: 'DI Mountain Region' },
                { id: '4691', name: 'DI South Central Region' },
                { id: '4690', name: 'DI South Region' },
                { id: '4692', name: 'DI Southeast Region' },
                { id: '4693', name: 'DI West Region' },
                { id: '4756', name: 'ACC' },
                { id: '4750', name: 'ASUN' },
                { id: '4755', name: 'America East' },
                { id: '4754', name: 'Atlantic 10' },
                { id: '4782', name: 'BIG EAST' },
                { id: '4752', name: 'Big 12' },
                { id: '4757', name: 'Big Sky' },
                { id: '4758', name: 'Big South' },
                { id: '4759', name: 'Big Ten' },
                { id: '4760', name: 'Big West' },
                { id: '4762', name: 'CAA' },
                { id: '4761', name: 'Conference USA' },
                { id: '4784', name: 'HBCU' },
                { id: '4763', name: 'Horizon League' },
                { id: '4780', name: 'IC4A/ECAC' },
                { id: '4749', name: 'Ivy League' },
                { id: '4765', name: 'MEAC' },
                { id: '4773', name: 'Metro Atlantic' },
                { id: '4764', name: 'Mid-American' },
                { id: '4775', name: 'Missouri Valley' },
                { id: '4751', name: 'Mountain West' },
                { id: '4767', name: 'NEC' },
                { id: '4778', name: 'NEICAAA' },
                { id: '4777', name: 'Ohio Valley' },
                { id: '4768', name: 'Pac-12' },
                { id: '4772', name: 'Patriot League' },
                { id: '4766', name: 'SEC' },
                { id: '4769', name: 'SWAC' },
                { id: '4774', name: 'Southern Conference' },
                { id: '4748', name: 'Southland Conference' },
                { id: '4770', name: 'Sun Belt' },
                { id: '4781', name: 'The American' },
                { id: '4776', name: 'The Summit League' },
                { id: '4771', name: 'WAC' }
            ],
            'd2': [
                { id: '4516', name: '2024 Outdoor Qualifying List' },
                { id: '4543', name: 'DII Atlantic Region' },
                { id: '4544', name: 'DII Central Region' },
                { id: '4545', name: 'DII East Region' },
                { id: '4546', name: 'DII Midwest Region' },
                { id: '4547', name: 'DII South Central Region' },
                { id: '4548', name: 'DII South Region' },
                { id: '4549', name: 'DII Southeast Region' },
                { id: '4550', name: 'DII West Region' },
                { id: '4572', name: 'CACC' },
                { id: '4563', name: 'CCAA' },
                { id: '4552', name: 'CIAA' },
                { id: '4553', name: 'Conference Carolinas' },
                { id: '4566', name: 'ECC' },
                { id: '4554', name: 'GLIAC' },
                { id: '4555', name: 'GLVC' },
                { id: '4556', name: 'GNAC' },
                { id: '4571', name: 'Great American' },
                { id: '4568', name: 'Great Midwest' },
                { id: '4570', name: 'Gulf South' },
                { id: '4784', name: 'HBCU' },
                { id: '4561', name: 'Lone Star' },
                { id: '4557', name: 'MIAA' },
                { id: '4567', name: 'Mountain East' },
                { id: '4558', name: 'Northeast-10' },
                { id: '4559', name: 'Northern Sun' },
                { id: '4542', name: 'PSAC' },
                { id: '4564', name: 'PacWest' },
                { id: '4565', name: 'Peach Belt' },
                { id: '4560', name: 'RMAC' },
                { id: '4562', name: 'SIAC' },
                { id: '4569', name: 'South Atlantic' }
            ],
            'd3': [
                { id: '4517', name: '2024 Outdoor Qualifying List' },
                { id: '4702', name: 'DIII East Region' },
                { id: '4696', name: 'DIII Great Lakes Region' },
                { id: '4701', name: 'DIII Metro Region' },
                { id: '4697', name: 'DIII Mid-Atlantic Region' },
                { id: '4703', name: 'DIII Mideast Region' },
                { id: '4698', name: 'DIII Midwest Region' },
                { id: '4694', name: 'DIII Niagara Region' },
                { id: '4695', name: 'DIII North Region' },
                { id: '4699', name: 'DIII South Region' },
                { id: '4700', name: 'DIII West Region' },
                { id: '4741', name: 'AARTFC' },
                { id: '4715', name: 'American Rivers Conference' },
                { id: '4710', name: 'American Southwest' },
                { id: '4743', name: 'Atlantic East' },
                { id: '4713', name: 'CCIW' },
                { id: '4747', name: 'CCS' },
                { id: '4740', name: 'CSAC' },
                { id: '4708', name: 'CUNYAC' },
                { id: '4712', name: 'Centennial Conference' },
                { id: '4711', name: 'Coast-to-Coast' },
                { id: '4736', name: 'DIII All-Ohio' },
                { id: '4706', name: 'DIII New England' },
                { id: '4705', name: 'ECAC DIII' },
                { id: '4714', name: 'Empire 8' },
                { id: '4745', name: 'Great Northeast AC' },
                { id: '4784', name: 'HBCU' },
                { id: '4709', name: 'HCAC' },
                { id: '4716', name: 'Landmark Conference' },
                { id: '4717', name: 'Liberty League' },
                { id: '4718', name: 'Little East' },
                { id: '4719', name: 'MASCAC' },
                { id: '4723', name: 'MIAC' },
                { id: '4720', name: 'Michigan Intercollegiate AA' },
                { id: '4721', name: 'Middle Atlantic Conferences' },
                { id: '4722', name: 'Midwest Conference' },
                { id: '4727', name: 'NACC' },
                { id: '4778', name: 'NEICAAA' },
                { id: '4704', name: 'NESCAC' },
                { id: '4724', name: 'NEWMAC' },
                { id: '4725', name: 'NJAC' },
                { id: '4742', name: 'North Atlantic Conference' },
                { id: '4726', name: 'North Coast AC' },
                { id: '4728', name: 'Northwest Conference' },
                { id: '4730', name: 'ODAC' },
                { id: '4729', name: 'Ohio Athletic Conference' },
                { id: '4731', name: 'Presidents AC' },
                { id: '4707', name: 'SCAC' },
                { id: '4737', name: 'SCIAC' },
                { id: '4738', name: 'SLIAC' },
                { id: '4732', name: 'SUNYAC' },
                { id: '4739', name: 'Southern Athletic Association' },
                { id: '4733', name: 'UAA' },
                { id: '4734', name: 'UMAC' },
                { id: '4744', name: 'USA South' },
                { id: '4785', name: 'United East/AMCC' },
                { id: '4735', name: 'WIAC' }
            ],
            'naia': [
                { id: '4518', name: '2024 Outdoor Qualifying List' },
                { id: '4587', name: 'American Midwest' },
                { id: '4589', name: 'Appalachian AC' },
                { id: '4581', name: 'Cascade Conference' },
                { id: '4591', name: 'Chicagoland Collegiate' },
                { id: '4588', name: 'Crossroads League' },
                { id: '4593', name: 'Frontier Conference' },
                { id: '4578', name: 'Golden State AC' },
                { id: '4576', name: 'Great Plains AC' },
                { id: '4784', name: 'HBCU' },
                { id: '4575', name: 'Heart of America AC' },
                { id: '4585', name: 'KCAC' },
                { id: '4583', name: 'Mid-South Conference' },
                { id: '4584', name: 'North Star' },
                { id: '4590', name: 'River States Conference' },
                { id: '4592', name: 'Sooner AC' },
                { id: '4586', name: 'Southern States AC' },
                { id: '4577', name: 'The Sun Conference' },
                { id: '4580', name: 'WHAC' }
            ],
            'njcaa': [
                { id: '4685', name: '2024 Outdoor Qualifying List' },
                { id: '4519', name: 'NJCAA Div. I' },
                { id: '4520', name: 'NJCAA Div. III' },
                { id: '4523', name: 'NWAC' },
                { id: '4540', name: 'Big 8' },
                { id: '4530', name: 'CCC' },
                { id: '4533', name: 'Coast' },
                { id: '4534', name: 'Golden Valley' },
                { id: '4531', name: 'NorCal' },
                { id: '4536', name: 'Orange Empire' },
                { id: '4537', name: 'Pacific Coast' },
                { id: '4532', name: 'SoCal' },
                { id: '4538', name: 'South Coast' },
                { id: '4539', name: 'Western State' }
            ],
            'nccaa': [
                { id: '4521', name: '2024 Outdoor Qualifying List' }
            ]
        },
        '2025_in': {
            d1: [
                { id: '4867', name: "2025 Indoor Qualifying List" },
                { id: '4873', name: "DI Great Lakes Region" },
                { id: '4875', name: "DI Mid-Atlantic Region" },
                { id: '4876', name: "DI Midwest Region" },
                { id: '4877', name: "DI Mountain Region" },
                { id: '4878', name: "DI Northeast Region" },
                { id: '4880', name: "DI South Central Region" },
                { id: '4879', name: "DI South Region" },
                { id: '4881', name: "DI Southeast Region" },
                { id: '4882', name: "DI West Region" },
                { id: '4909', name: "ACC" },
                { id: '4904', name: "ASUN" },
                { id: '4908', name: "America East" },
                { id: '4907', name: "Atlantic 10" },
                { id: '4931', name: "BIG EAST" },
                { id: '4906', name: "Big 12" },
                { id: '4910', name: "Big Sky" },
                { id: '4911', name: "Big South" },
                { id: '4912', name: "Big Ten" },
                { id: '4914', name: "CAA" },
                { id: '4913', name: "Conference USA" },
                { id: '4915', name: "Horizon League" },
                { id: '4929', name: "IC4A/ECAC" },
                { id: '4903', name: "Ivy League" },
                { id: '4917', name: "MEAC" },
                { id: '4933', name: "MPSF" },
                { id: '4923', name: "Metro Atlantic" },
                { id: '4928', name: "Mets" },
                { id: '4916', name: "Mid-American" },
                { id: '4925', name: "Missouri Valley" },
                { id: '4905', name: "Mountain West" },
                { id: '4935', name: "NEC" },
                { id: '4934', name: "NEICAAA" },
                { id: '4926', name: "Ohio Valley" },
                { id: '4922', name: "Patriot League" },
                { id: '4918', name: "SEC" },
                { id: '4919', name: "SWAC" },
                { id: '4924', name: "Southern Conference" },
                { id: '4891', name: "Southland Conference" },
                { id: '4920', name: "Sun Belt" },
                { id: '4930', name: "The American" },
                { id: '4927', name: "The Summit League" },
                { id: '4921', name: "WAC" }
            ],
            d2: [
                { id: '4868', name: "2025 Indoor Qualifying List" },
                { id: '4883', name: "DII Atlantic Region" },
                { id: '4884', name: "DII Central Region" },
                { id: '4885', name: "DII East Region" },
                { id: '4886', name: "DII Midwest Region" },
                { id: '4887', name: "DII South Central Region" },
                { id: '4888', name: "DII South Region" },
                { id: '4889', name: "DII Southeast Region" },
                { id: '4890', name: "DII West Region" },
                { id: '4937', name: "CIAA" },
                { id: '4938', name: "Conference Carolinas" },
                { id: '4948', name: "ECC" },
                { id: '4939', name: "GLIAC" },
                { id: '4940', name: "GLVC" },
                { id: '4941', name: "GNAC" },
                { id: '4950', name: "Great Midwest" },
                { id: '4952', name: "Gulf South" },
                { id: '4932', name: "HBCU" },
                { id: '4946', name: "Lone Star" },
                { id: '4942', name: "MIAA" },
                { id: '4949', name: "Mountain East" },
                { id: '4934', name: "NEICAAA" },
                { id: '4943', name: "Northeast-10" },
                { id: '4944', name: "Northern Sun" },
                { id: '4936', name: "PSAC" },
                { id: '4947', name: "Peach Belt" },
                { id: '4945', name: "RMAC" },
                { id: '4951', name: "South Atlantic" }
            ],
            d3: [
                { id: '4869', name: "2025 Indoor Qualifying List" },
                { id: '4901', name: "DIII East Region" },
                { id: '4895', name: "DIII Great Lakes Region" },
                { id: '4900', name: "DIII Metro Region" },
                { id: '4896', name: "DIII Mid-Atlantic Region" },
                { id: '4902', name: "DIII Mideast Region" },
                { id: '4897', name: "DIII Midwest Region" },
                { id: '4893', name: "DIII Niagara Region" },
                { id: '4894', name: "DIII North Region" },
                { id: '4898', name: "DIII South Region" },
                { id: '4899', name: "DIII West Region" },
                { id: '4999', name: "AARTFC" },
                { id: '4959', name: "American Rivers Conference" },
                { id: '4961', name: "CCIW" },
                { id: '4953', name: "CUNYAC" },
                { id: '4956', name: "Centennial Conference" },
                { id: '4955', name: "Coast-to-Coast" },
                { id: '4892', name: "DIII New England" },
                { id: '4958', name: "Empire 8" },
                { id: '4983', name: "Frozen 8" },
                { id: '4982', name: "Great Northeast AC" },
                { id: '4954', name: "HCAC" },
                { id: '4929', name: "IC4A/ECAC" },
                { id: '4960', name: "Landmark Conference" },
                { id: '4962', name: "Liberty League" },
                { id: '4963', name: "Little East" },
                { id: '4964', name: "MASCAC" },
                { id: '4968', name: "MIAC" },
                { id: '4965', name: "Michigan Intercollegiate AA" },
                { id: '4966', name: "Middle Atlantic Conferences" },
                { id: '4967', name: "Midwest Conference" },
                { id: '4970', name: "NACC" },
                { id: '4934', name: "NEICAAA" },
                { id: '4969', name: "NJAC" },
                { id: '4985', name: "North Coast AC" },
                { id: '4971', name: "Northwest Conference" },
                { id: '4972', name: "ODAC" },
                { id: '4973', name: "Ohio Athletic Conference" },
                { id: '4974', name: "Presidents AC" },
                { id: '4979', name: "SLIAC" },
                { id: '4975', name: "SUNYAC" },
                { id: '4980', name: "Southern Athletic Association" },
                { id: '4976', name: "UAA" },
                { id: '4977', name: "UMAC" },
                { id: '4981', name: "USA South" },
                { id: '4978', name: "WIAC" }
            ],
            naia: [
                { id: '4518', name: '2024 Outdoor Qualifying List' },
                { id: '4994', name: 'American Midwest' },
                { id: '4996', name: 'Appalachian AC' },
                { id: '4998', name: 'Chicagoland Collegiate (NAIA)' },
                { id: '4995', name: 'Crossroads League (NAIA)' },
                { id: '4987', name: 'Great Plains AC (NAIA)' },
                { id: '4986', name: 'Heart of America AC (NAIA)' },
                { id: '4989', name: 'KCAC (NAIA)' },
                { id: '4992', name: 'Mid-South Conference (NAIA)' },
                { id: '4993', name: 'North Star (NAIA)' },
                { id: '4997', name: 'River States Conference (NAIA)' },
                { id: '4991', name: 'Southern States AC (NAIA)' },
                { id: '4988', name: 'The Sun Conference (NAIA)' },
                { id: '4990', name: 'WHAC (NAIA)' }
            ],
            njcaa: [
                { id: '4871', name: '2025 Indoor Qualifying List' }
            ],
            nccaa: [
                { id: '4872', name: '2025 Indoor Qualifying List'}
            ]
        }
    };

    function updatePerformanceList() {
        const selectedSeason = seasonSelect.value;
        const selectedDivision = divisionSelect.value;

        perflistSelect.innerHTML = '<option value="default">-Select-</option>';

        if (selectedSeason in performanceLists && selectedDivision in performanceLists[selectedSeason]) {
            const lists = performanceLists[selectedSeason][selectedDivision];
            lists.forEach(list => {
                const option = document.createElement('option');
                option.value = list.id;
                option.textContent = list.name;
                perflistSelect.appendChild(option);
            });
        }
    }

    seasonSelect.addEventListener('change', updatePerformanceList);
    divisionSelect.addEventListener('change', updatePerformanceList);
});
